### ISSUE TITLE
Error when trying to use diff from immutablediff, is RFC 6902 patch compatible?

### ISSUE THREAD

**Issue by jeffbski** [zaim/immpatch#1]
I was assuming from the README that I should be able to use a diff generated from immutablediff with immpatch, so I tried the following simple test and it gave me an error.

Is immpatch supposed to be compatible with RFC 6902 style patches that immutablediff generates?

``` javascript
var diff = require('immutablediff');
var Immutable = require('immutable');
var patch = require('immpatch');

var m1 = Immutable.fromJS({ foo: { bar: 1 }});
console.log('m1', m1);

var m2 = m1.setIn(['foo', 'cat'], 2);
console.log('m2', m2);

var d = diff(m1, m2);
console.log('d', d);

var p = patch(m1, d);
console.log('p', p);
```

throws error

```
Invalid Operation object "op" member must be one of add, remove, replace, move, copy, test but got "undefined" operation: undefined
```

Thanks in advance for your help.

**Comment by zaim** [comment]
I think the issue is that immutablediff returns an Immutable.js `List` object as the patch/ops "array", whereas immpatch expects a plain javascript array. To fix it simply call `d.toJS()`, like so:

``` javascript
var diff = require('immutablediff');
var Immutable = require('immutable');
var patch = require('immpatch');

var m1 = Immutable.fromJS({ foo: { bar: 1 }});
console.log('m1', m1);

var m2 = m1.setIn(['foo', 'cat'], 2);
console.log('m2', m2);

var d = diff(m1, m2);
console.log('d', d);

var p = patch(m1, d.toJS());  // <-- converts the List to a plain Array
console.log('p', p);
```

I'll be updating the README with better documentation of the API. Plus, looking at the error message, I might update it to provide a more useful one (e.g. "patch expects ops argument to be an Array, got List")

Thanks for reporting this!

**Comment by jeffbski** [comment]
Great, thanks for getting back to me, yes that seems to fix the issue.
